export const state = {
	catalog: null,
	ankiStatus: null,
	ankiStatusLoading: false,
	ankiStatusError: "",
	ankiStatusSource: null,
	moyangAnkiStatus: null,
	huneumAnkiStatus: null,
	huneumAnkiStatusSource: "",
	idiomAnkiStatus: null,
	knownWords: new Set(),
	markedWords: new Set(),
	knownWordsSource: "",
	selected: new Set(),
	vocabulary: [],
	vocabularyTotal: 0,
	idioms: null,
};
